### PR TITLE
add targetLanguage setting

### PR DESCRIPTION
**Pull request by Osilos**
Hello @addyi 

I love your extension, but I'm not a german speaker. Then I add a setting in your extension to choose the target language. (german or french)

Are you ok to integrate this in your extension ?

I saw you used /search?source=auto maybe you use the extension to target non english text ? 

Tell me, I'm sure we can find a way to autodetect the language :)

### CODE REVIEW

**Comment by addyi** [comment]
Hi @Osilos 

thanks for the pull request. This is a great idea. I will test it and upload the update to the chrome marketplace. This could take a few days, because I am very busy at the moment.

I generally translate english to german, but the option to change or detect the source language seems also important for other people or improves the convenience. If you got an idea I am happy to work on it.

**Comment by Osilos** [comment]
To auto detect the source target we can use google traduction api : [`https://cloud.google.com/translate/docs/detecting-language`](https://cloud.google.com/translate/docs/detecting-language)

I don't find anything similar on Linguee

**Comment by addyi** [comment]
I looked at the problem again when I wanted to merge the pull requst #1 and probably found a simpler solution.

I have noticed that Linguee uses different top level domains or sub domains for the languages:

- linguee.com
- linguee.fr
- linguee.de
- cn.linguee.com
- fi.linguee.com
- etc.

So if we create a setting for the prefered mother tongue of the user we should only need to change the domain and can keep `?source=auto&query=`. 

@Osilos  What do you think of this solution?

**Comment by Osilos** [comment]
@addyi Yes I think it's a good idea ! I didn't notice that. I will work on that :)

**Comment by addyi** [comment]
@Osilos  That would be cool if you would update the pull request. You would help me a lot with this, as I have many projects and obligations right now. I haven't even managed to take care of my idea to open a popup instead of opening a tab every time #2.

**Comment by Osilos** [comment]
@addyi I will work tomorrow on this PR :)

for #2 I think it's a good idea, and I thought about this too. If I got time I'll work on that too, but first I want to end this PR.

**Comment by Osilos** [comment]
Hi @addyi 

I update the PR. Now the plugins handle all the language available on Linguee. And it work with autodetect. And I add some style on the pop up. 

I think it can be improve but it's a good start. To improve the style of the pop up we have to wonder about keep it light, I was looking to include some css framework on it, but finally I think it's overkill.

I'll be happy to see the extension on the store with this PR :)

**Comment by addyi** [comment]
I have noticed two small bugs.

- target lang could be undefined
- document.getElementById('target') was null

@Osilos Are these changes okay with you?

**Comment by Osilos** [comment]
@addyi Yes ofc ! 

You right, I didn't catch this bugs, nice fix !

**Comment by addyi** [comment]
@Osilos Thanks for the work. It should be updated soon 👍

**Comment by jrd10** [comment]
Hi, thank you for this extension.
I think the extension is still in "English to German" mode only. 
Even if you target the English language.
Even if you use a .fr source web site.
Thank you if you can confirm you have already implémented a functionality allowing to target the source language or if you think to implement it soon.

mit freundlichen Grüßen (as Linguee was in German :).
José

**Comment by Osilos** [comment]
Hi @JRelland 

You can choose your target language in the extension settings. And on my test it looks right when you target English. But sometimes it fails to recognize the source language, and fallback on german (I guess). It seems to be more a bug on Linguee side. The extension use the Linguee API.

One way to fix this can be to have a setting to force the source language. Then the extension will stop using autodetect language.

I'll work on that :)

**Comment by jrd10** [comment]
Hi, thanks toi for this feedback.

**Comment by addyi** [comment]
Hi @JRelland,
Hi @Osilos,

Cool that you are helping each other. 
I also made the same observation as @Osilos and think this can't be solved without a force to language combinations like de-en, en-de, fr-de, de-fr, fr-en, en-fr, …
Currently I am not able to work on the plug-in, but I am happy to review a pull request.

Viele Grüße

addyi

**Comment by jrd10** [comment]
Thank you for this feedback.

Unfortunately, I am unable to code...

That is why would like to thank you again for sharing your time and
knowledge for the community.
Thank you for this application.


-- 
Cordialement

M. José RELLAND
jose.relland@gmail.com
+33 (0)6 79 48 49 97
Skype: jose.relland.job

[+] Please keep my contact details up-to-date
<https://ws.evercontact.com/kwaga-bin/titan/WEB/me.pl/2931835391445501472/i>


Le lun. 1 avr. 2019 à 16:36, Adrian Renner <notifications@github.com> a
écrit :

**Comment by Herbert-Khrill** [comment]
Same issue for me here : i want to translate from german to french but it doesn't work and only propose german to english or french to english when i change the target language.
Have you a solution yet ?
Thanks

**Pull request merged**
